name = "administer_org/administer"
version = "0.1.0"
description = "Administer is a modular admin panel for Roblox."
authors = ["FloofyPlasma", "pyxfluff"]
repository = "https://github.com/administer-org/administer"
license = "AGPL-3.0"

[target]
environment = "roblox"

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }
