name: Continuous Build

on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Pesde
              uses: lumin-org/setup-pesde@v0.3.2
              with:
                cache: true

            - name: Install Packages
              run: pesde install

            - name: Build
              run: rojo build build.project.json --output ./Administer.rbxm

            - name: Set short SHA
              run: echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV

            - name: Release
              uses: softprops/action-gh-release@v2.2.1
              with:
                tag_name: build_${{ env.SHORT_SHA }}
                name: CI Build
                prerelease: true
                generate_release_notes: true
                body: |
                  Built at ${{ github.event.repository.updated_at }}
                  Latest commit: ${{ github.sha }}
                  Created by ${{ github.actor }}
                files: |
                 ./Administer.rbxm

